// src/data/technologyData.ts

import { TechnologyCategory, BannerContent } from "@/types/technology/technology";

export const technologyCategories: TechnologyCategory[] = [
  {
    id: "mobile",
    title: "Mobile",
    technologies: [
      { name: "iOS", icon: "" },
      { name: "Android", icon: "" },
      { name: "React Native", icon: "" },
      { name: "Flutter", icon: "" },
      { name: "PWA", icon: "" },
      { name: "Ionic", icon: "" },
      { name: "Xamarin", icon: "" },
      { name: "Kotlin", icon: "" },
      { name: "Swift", icon: "" },
    ],
  },
  {
    id: "cloud",
    title: "Cloud",
    technologies: [
      { name: "AWS", icon: "" },
      { name: "Azure", icon: "" },
      { name: "Bitrix", icon: "" },
      { name: "Google Cloud", icon: "" },
      { name: "IBM Cloud", icon: "" },
      { name: "Oracle Cloud", icon: "" },
    ],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    technologies: [
      { name: "Cybersecurity Consulting", icon: "" },
      { name: "VAPT", icon: "" },
      { name: "Infrastructure Monitoring", icon: "" },
      { name: "Application Security", icon: "" },
      { name: "Red Teaming", icon: "" },
      { name: "SCA", icon: "" },
      { name: "Social Engineering", icon: "" },
      { name: "DLM", icon: "" },
      { name: "Cybersecurity Training", icon: "" },
      { name: "Penetration Testing", icon: "" },
      { name: "SIEM", icon: "" },
    ],
  },
  {
    id: "ai",
    title: "AI",
    technologies: [
      { name: "AI Consulting", icon: "" },
      { name: "AI Integration", icon: "" },
      { name: "AI ADC", icon: "" },
      { name: "AI Chatbot", icon: "" },
      { name: "AI Model", icon: "" },
      { name: "Customer Experience", icon: "" },
      { name: "SPES", icon: "" },
      { name: "Data Intelligence", icon: "" },
      { name: "Cloud Devops Services", icon: "" },
      { name: "NLPS", icon: "" },
      { name: "LLM", icon: "" },
      { name: "Computer Vision", icon: "" },
      { name: "NLP", icon: "" },
      { name: "Deep Learning", icon: "" },
      { name: "Machine Learning", icon: "" },
      { name: "TensorFlow", icon: "" },
      { name: "PyTorch", icon: "" },
    ],
  },
  {
    id: "cms",
    title: "CMS",
    technologies: [
      { name: "Shopify", icon: "" },
      { name: "WordPress", icon: "" },
      { name: "Magento", icon: "" },
      { name: "Prestashop", icon: "" },
      { name: "Drupal", icon: "" },
      { name: "Frontend", icon: "" },
      { name: "React Js", icon: "" },
      { name: "Angular Js", icon: "" },
      { name: "Adobe Commerce", icon: "" },
      { name: "Joomla", icon: "" },
      { name: "Contentful", icon: "" },
      { name: "Strapi", icon: "" },
    ],
  },
  {
    id: "web3",
    title: "Web 3.0",
    technologies: [
      { name: "Web 3.0", icon: "" },
      { name: "Blockchain", icon: "" },
      { name: "Artificial Intelligence", icon: "" },
      { name: "Augmented Reality", icon: "" },
      { name: "Virtual Reality", icon: "" },
      { name: "Mixed Reality", icon: "" },
      { name: "DApps", icon: "" },
      { name: "NFTs", icon: "" },
      { name: "Smart Contracts", icon: "" },
      { name: "Solidity", icon: "" },
    ],
  },
  {
    id: "backend",
    title: "Backend",
    technologies: [
      { name: "Java", icon: "" },
      { name: ".Net", icon: "" },
      { name: "Node Js", icon: "" },
      { name: "Django", icon: "" },
      { name: "Python", icon: "" },
      { name: "Laravel", icon: "" },
      { name: "PHP", icon: "" },
      { name: "Spring Boot", icon: "" },
      { name: "Express.js", icon: "" },
      { name: "Flask", icon: "" },
      { name: "ASP.NET", icon: "" },
    ],
  },
  {
    id: "fullstack",
    title: "Full Stack",
    technologies: [
      { name: "MERN", icon: "" },
      { name: "MEAN", icon: "" },
      { name: "ROR", icon: "" },
      { name: "LAMP", icon: "" },
      { name: "JAMstack", icon: "" },
      { name: "Full-Stack Serverless", icon: "" },
    ],
  },
  {
    id: "trending",
    title: "Trending",
    technologies: [
      { name: "Generative AI", icon: "" },
      { name: "Edge Computing", icon: "" },
      { name: "IoT", icon: "" },
      { name: "Quantum Computing", icon: "" },
    ],
  },
  {
    id: "devops",
    title: "DevOps",
    technologies: [
      { name: "Jenkins", icon: "" },
      { name: "GitLab CI", icon: "" },
      { name: "CircleCI", icon: "" },
      { name: "Docker", icon: "" },
      { name: "Kubernetes", icon: "" },
      { name: "OpenShift", icon: "" },
      { name: "Terraform", icon: "" },
      { name: "Ansible", icon: "" },
      { name: "Puppet", icon: "" },
      { name: "Prometheus", icon: "" },
      { name: "Grafana", icon: "" },
      { name: "ELK Stack", icon: "" },
      { name: "Git", icon: "" },
      { name: "Bitbucket", icon: "" },
    ],
  },
  {
    id: "dataengineering",
    title: "Data Engineering",
    technologies: [
      { name: "Hadoop", icon: "" },
      { name: "Apache", icon: "" },
      { name: "Spark", icon: "" },
      { name: "Snowflake", icon: "" },
      { name: "Amazon", icon: "" },
      { name: "Redshift", icon: "" },
      { name: "Google", icon: "" },
      { name: "BigQuery", icon: "" },
      { name: "Apache NiFi", icon: "" },
      { name: "Talend", icon: "" },
      { name: "Informatica", icon: "" },
      { name: "Azure Data Lake", icon: "" },
      { name: "AWS Lake Formation", icon: "" },
      { name: "Apache Kafka", icon: "" },
      { name: "AWS Glue", icon: "" },
      { name: "Google Dataflow", icon: "" },
    ],
  },
  {
    id: "mbaas",
    title: "MBaaS",
    technologies: [
      { name: "Firebase", icon: "" },
      { name: "AWS Amplify", icon: "" },
      { name: "Backendless", icon: "" },
      { name: "OneSignal", icon: "" },
      { name: "Firebase Cloud Messaging", icon: "" },
      { name: "Firebase Realtime Database", icon: "" },
      { name: "AWS AppSync", icon: "" },
    ],
  },
  {
    id: "qa",
    title: "Quality Assurance & Testing",
    technologies: [
      { name: "Selenium", icon: "" },
      { name: "TestNG", icon: "" },
      { name: "Appium", icon: "" },
      { name: "Cypress", icon: "" },
      { name: "JMeter", icon: "" },
      { name: "LoadRunner", icon: "" },
      { name: "Gatling", icon: "" },
      { name: "OWASP ZAP", icon: "" },
      { name: "Burp Suite", icon: "" },
      { name: "SonarQube", icon: "" },
      { name: "Bamboo", icon: "" },
    ],
  },
  {
    id: "api",
    title: "API Management",
    technologies: [
      { name: "Kong", icon: "" },
      { name: "Apigee", icon: "" },
      { name: "AWS API Gateway", icon: "" },
      { name: "Swagger", icon: "" },
      { name: "Postman", icon: "" },
      { name: "API Blueprint", icon: "" },
      { name: "OAuth2", icon: "" },
      { name: "JWT", icon: "" },
      { name: "API Fortress", icon: "" },
    ],
  },
  {
    id: "arvr",
    title: "AR/VR/XR",
    technologies: [
      { name: "Unity", icon: "" },
      { name: "Unreal Engine", icon: "" },
      { name: "ARCore", icon: "" },
      { name: "ARKit", icon: "" },
      { name: "Vuforia", icon: "" },
      { name: "Oculus SDK", icon: "" },
      { name: "HTC Vive SDK", icon: "" },
      { name: "Microsoft HoloLens", icon: "" },
      { name: "Magic Leap", icon: "" },
    ],
  },
];


export const technologyBannerData: BannerContent = {
  mainTitle: "Arsenal of Technologies",
  subTitle: "We Empower Businesses With",
  backgroundImage: "/images/technologies/technologies_banner.jpg"
};